package com.biprom.terweze.Designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainMenuDesing extends HorizontalLayout {
    protected Button menuButton;
    protected CssLayout menu;
    protected Button bLeefruimte;
    protected Button bKeuken;
    protected Button bBuiten;
    protected Button bGarage;
    protected Button bSlaapkamer;
    protected Button bFitness;
    protected Button bNachthall;
    protected Button bBadkamer;
    protected Button bInkom;
    protected Button bBerging;
    protected Button bWijnkelder;
    protected CssLayout content;
    protected CssLayout subPanel;

    public MainMenuDesing() {
        Design.read(this);
    }
}
